server:
  port: 8085
  # Port number for Aggregator service

spring:
  application:
    name: PRICEWISE-AGGREGATOR
    # Service name for Eureka registration

  data:
    redis:
      host: redis
      # Redis host name (Docker service name)
      port: 6379
      # Redis port number

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      # Eureka server URL

  instance:
    leaseRenewalIntervalInSeconds: 30
    # Heartbeat interval in seconds, Service sends a renewal every 30 seconds to Eureka
    leaseExpirationDurationInSeconds: 90
    # Expiration duration in seconds, If no heartbeat is received within 90 seconds, Eureka removes the service
